/*******************************************************************************
 * Copyright 2015 SteveKunG - More Planets Mod
 * 
 * This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
 ******************************************************************************/

package stevekung.mods.moreplanets.planets.fronos.blocks;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.oredict.OreDictionary;
import stevekung.mods.moreplanets.common.blocks.BlockBaseMP;
import stevekung.mods.moreplanets.common.blocks.BlockBushMP;
import stevekung.mods.moreplanets.common.blocks.BlockDoorMP;
import stevekung.mods.moreplanets.common.blocks.BlockDoorMP.DoorType;
import stevekung.mods.moreplanets.common.blocks.BlockFenceGateMP;
import stevekung.mods.moreplanets.common.blocks.BlockSnowLayerMP;
import stevekung.mods.moreplanets.common.blocks.BlockStairsMP;
import stevekung.mods.moreplanets.common.blocks.BlockVineMP;
import stevekung.mods.moreplanets.common.blocks.fluid.FluidMP;
import stevekung.mods.moreplanets.common.itemblocks.ItemBlockColoredMP;
import stevekung.mods.moreplanets.common.itemblocks.ItemBlockMultiVariant;
import stevekung.mods.moreplanets.common.itemblocks.ItemBlockMultiVariantLeaves;
import stevekung.mods.moreplanets.common.itemblocks.ItemBlockSnowLayerMP;
import stevekung.mods.moreplanets.common.util.VariantsName;
import stevekung.mods.moreplanets.planets.fronos.blocks.fluids.BlockFluidCaramel;
import stevekung.mods.moreplanets.planets.fronos.blocks.fluids.BlockFluidCoconutMilk;
import stevekung.mods.moreplanets.planets.fronos.blocks.fluids.BlockFluidMineralWater;
import stevekung.mods.moreplanets.planets.fronos.blocks.fluids.BlockFluidOvaltine;
import stevekung.mods.moreplanets.planets.fronos.blocks.fluids.BlockFluidTea;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockCandyCane1;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockCandyCane2;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockDandelion;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockFronosColorizedLeaves;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockFronosLog;
import stevekung.mods.moreplanets.planets.fronos.itemblocks.ItemBlockFronosSandstoneSlab;
import stevekung.mods.moreplanets.planets.fronos.items.FronosItems;
import stevekung.mods.stevecore.CommonRegisterHelper;

public class FronosBlocks
{
    public static Block fronos_grass;
    public static Block plains_grass;
    public static Block pink_grass;
    public static Block purple_grass;
    public static Block golden_grass;
    public static Block fronos_dirt;
    public static Block fronos_block;
    public static Block fronos_block1;
    public static Block jelly_ore;
    public static Block ore_block;
    public static Block frosted_cake;
    public static Block jelly_block;
    public static Block cookie_block;
    public static Block ovaltine_block;
    public static Block chocolate_block;
    public static Block caramel_block;
    public static Block cloud_block;
    public static Block candy_cane1;
    public static Block candy_cane2;
    public static Block cream_block;
    public static Block vanilla_cream_layer;
    public static Block chocolate_cream_layer;
    public static Block strawberry_cream_layer;
    public static Block orange_cream_layer;
    public static Block tea_cream_layer;
    public static Block lemon_cream_layer;
    public static Block fronos_sand;
    public static Block cheese_glass;
    public static Block cheese_glass_pane;
    public static Block fronos_log;
    public static Block fronos_planks;
    public static Block fronos_colorized_leaves;
    public static Block fronos_leaves;
    public static Block fronos_cobblestone_stairs;
    public static Block fronos_stone_brick_stairs;
    public static Block cracked_fronos_stone_brick_stairs;
    public static Block fronos_dungeon_brick_stairs;
    public static Block coconut_wood_stairs;
    public static Block maple_wood_stairs;
    public static Block fronos_fence;
    public static Block coconut_fence_gate;
    public static Block maple_fence_gate;
    public static Block fronos_treasure_chest;
    public static Block fronos_ancient_chest;
    public static Block candy_extractor_idle;
    public static Block mineral_water_generator;
    public static Block candy_extractor_active;
    public static Block fronos_farmland;
    public static Block strawberry_bush;
    public static Block golden_crops;
    public static Block coconut_block;
    public static Block golem_cream_head;
    public static Block cake_bread;
    public static Block white_cake_bread;
    public static Block chocolate_cake_bread;
    public static Block pink_cake;
    public static Block white_cake;
    public static Block chocolate_cake;
    public static Block space_shell;
    public static Block space_oyster;
    public static Block cavern_oyster;
    public static Block jelly_slime_egg;
    public static BlockBushMP fronos_sapling;
    public static BlockBushMP fronos_tall_grass;
    public static BlockBushMP fronos_flower;
    public static BlockBushMP fronos_dandelion;
    public static BlockBushMP fronos_poppy;
    public static BlockBushMP candy_flower;
    public static BlockBushMP fronos_coral;
    public static Block cheese_web;
    public static Block glass_gem_corn;
    public static Block red_maple_ivy;
    public static Block yellow_maple_ivy;
    public static Block purple_maple_ivy;
    public static Block pink_candy_torch;
    public static Block orange_candy_torch;
    public static Block green_candy_torch;
    public static Block yellow_candy_torch;
    public static Block light_blue_candy_torch;
    public static Block blue_candy_torch;
    public static Block red_candy_torch;
    public static Block purple_candy_torch;
    public static Block cup;
    public static Block mineral_water_cup;
    public static Block ovaltine_cup;
    public static Block coconut_milk_cup;
    public static Block cheese_of_milk_cup;
    public static Block tea_cup;
    public static Block caramel_cup;
    public static Block coconut_door_block;
    public static Block maple_door_block;
    public static Block coconut_milk;
    public static Block mineral_water;
    public static Block ovaltine;
    public static Block tea;
    public static Block caramel;
    public static Block fronos_sandstone;
    public static Block half_fronos_sandstone_slab;
    public static Block double_fronos_sandstone_slab;
    public static Block fronos_sandstone_stairs;
    public static Block white_sandstone_stairs;
    public static Block cheese_sandstone_stairs;
    public static Block fronos_double_tallgrass;
    public static Block sky_mushroom_block;
    public static Block cake_farmland;

    public static Fluid coconut_milk_fluid;
    public static Fluid mineral_water_fluid;
    public static Fluid ovaltine_fluid;
    public static Fluid tea_fluid;
    public static Fluid caramel_fluid;

    public static void init()
    {
        // Init
        FronosBlocks.fronos_grass = new BlockFronosGrass("fronos_grass");
        FronosBlocks.plains_grass = new BlockPlainsGrass("plains_grass");
        FronosBlocks.pink_grass = new BlockPinkGrass("pink_grass");
        FronosBlocks.purple_grass = new BlockPurpleGrass("purple_grass");
        FronosBlocks.golden_grass = new BlockGoldenGrass("golden_grass");
        FronosBlocks.fronos_dirt = new BlockFronosDirt("fronos_dirt");
        FronosBlocks.fronos_block = new BlockFronos("fronos_block");
        FronosBlocks.fronos_block1 = new BlockFronos1("fronos_block1");
        FronosBlocks.jelly_ore = new BlockJellyOre("jelly_ore");
        FronosBlocks.ore_block = new BlockOreFronos("fronos_ore_block");
        FronosBlocks.frosted_cake = new BlockFrostedCake("frosted_cake_block");
        FronosBlocks.jelly_block = new BlockJelly("jelly_block");
        FronosBlocks.cookie_block = new BlockCookie("cookie_block");
        FronosBlocks.ovaltine_block = new BlockOvaltine("ovaltine_block");
        FronosBlocks.chocolate_block = new BlockBaseMP("chocolate_block", Material.clay).setStepSound(Block.soundTypeSnow).setHardness(0.55F);
        FronosBlocks.caramel_block = new BlockCaramel("caramel_block");
        FronosBlocks.cloud_block = new BlockFronosCloud("fronos_cloud");
        FronosBlocks.candy_cane1 = new BlockCandyCane1("candy_cane1");
        FronosBlocks.candy_cane2 = new BlockCandyCane2("candy_cane2");
        FronosBlocks.cream_block = new BlockCream("cream_block");
        FronosBlocks.vanilla_cream_layer = new BlockSnowLayerMP("vanilla_cream_layer", FronosItems.cream_ball, 0);
        FronosBlocks.chocolate_cream_layer = new BlockSnowLayerMP("chocolate_cream_layer", FronosItems.cream_ball, 1);
        FronosBlocks.strawberry_cream_layer = new BlockSnowLayerMP("strawberry_cream_layer", FronosItems.cream_ball, 2);
        FronosBlocks.orange_cream_layer = new BlockSnowLayerMP("orange_cream_layer", FronosItems.cream_ball, 3);
        FronosBlocks.tea_cream_layer = new BlockSnowLayerMP("tea_cream_layer", FronosItems.cream_ball, 4);
        FronosBlocks.lemon_cream_layer = new BlockSnowLayerMP("lemon_cream_layer", FronosItems.cream_ball, 5);
        FronosBlocks.fronos_sand = new BlockFronosSand("fronos_sand");
        FronosBlocks.cheese_glass = new BlockCheeseGlass("cheese_glass");
        FronosBlocks.cheese_glass_pane = new BlockCheeseGlassPane("cheese_glass_pane");
        FronosBlocks.fronos_log = new BlockFronosLog("fronos_log");
        FronosBlocks.fronos_planks = new BlockFronosPlanks("fronos_planks");
        FronosBlocks.fronos_colorized_leaves = new BlockFronosColorizedLeaves("fronos_leaves");
        FronosBlocks.fronos_leaves = new BlockFronosLeaves("fronos_leaves2");
        FronosBlocks.fronos_cobblestone_stairs = new BlockStairsMP(Blocks.stone, "fronos_cobblestone_stairs", 1.5F);
        FronosBlocks.fronos_stone_brick_stairs = new BlockStairsMP(Blocks.stone, "fronos_stone_brick_stairs", 1.5F);
        FronosBlocks.cracked_fronos_stone_brick_stairs = new BlockStairsMP(Blocks.stone, "cracked_fronos_stone_brick_stairs", 1.5F);
        FronosBlocks.fronos_dungeon_brick_stairs = new BlockStairsMP(Blocks.stone, "fronos_dungeon_brick_stairs", 4.0F);
        FronosBlocks.coconut_wood_stairs = new BlockStairsMP(Blocks.planks, "coconut_wood_stairs", "wood", null, 2.0F);
        FronosBlocks.maple_wood_stairs = new BlockStairsMP(Blocks.planks, "maple_wood_stairs", "wood", null, 2.0F);
        FronosBlocks.fronos_fence = new BlockFronosFence("fronos_fence");
        FronosBlocks.coconut_fence_gate = new BlockFenceGateMP("coconut_fence_gate");
        FronosBlocks.maple_fence_gate = new BlockFenceGateMP("maple_fence_gate");
        FronosBlocks.fronos_treasure_chest = new BlockFronosTreasureChest("fronos_treasure_chest");
        FronosBlocks.fronos_ancient_chest = new BlockFronosAncientChest("fronos_ancient_chest");
        FronosBlocks.candy_extractor_idle = new BlockCandyExtractor("candy_extractor_idle", false);
        FronosBlocks.mineral_water_generator = new BlockMineralWaterGenerator("mineral_water_generator");
        FronosBlocks.candy_extractor_active = new BlockCandyExtractor("candy_extractor_active", true);
        FronosBlocks.fronos_farmland = new BlockFronosFarmland("fronos_farmland");
        FronosBlocks.strawberry_bush = new BlockStrawberryBush("strawberry_bush");
        FronosBlocks.golden_crops = new BlockGoldenCrops("golden_crops");
        FronosBlocks.coconut_block = new BlockCoconut("coconut_block");
        FronosBlocks.golem_cream_head = new BlockGolemCreamHead("golem_cream_head");
        FronosBlocks.cake_bread = new BlockCakeBread("cake_bread");
        FronosBlocks.white_cake_bread = new BlockWhiteCakeBread("white_cake_bread");
        FronosBlocks.chocolate_cake_bread = new BlockChocolateCakeBread("chocolate_cake_bread");
        FronosBlocks.pink_cake = new BlockPinkCake("pink_cake");
        FronosBlocks.white_cake = new BlockWhiteCake("white_cake");
        FronosBlocks.chocolate_cake = new BlockChocolateCake("chocolate_cake");
        FronosBlocks.space_shell = new BlockSpaceShell("space_shell");
        FronosBlocks.space_oyster = new BlockSpaceOyster("space_oyster");
        FronosBlocks.cavern_oyster = new BlockCavernOyster("cavern_oyster");
        FronosBlocks.jelly_slime_egg = new BlockJellySlimeEgg("jelly_slime_egg");
        FronosBlocks.fronos_sapling = new BlockFronosSapling("fronos_sapling");
        FronosBlocks.fronos_tall_grass = new BlockFronosTallGrass("fronos_tall_grass");
        FronosBlocks.fronos_flower = new BlockFronosFlower("fronos_flower");
        FronosBlocks.fronos_dandelion = new BlockDandelion("fronos_dandelion");
        FronosBlocks.fronos_poppy = new BlockPoppy("fronos_poppy");
        FronosBlocks.candy_flower = new BlockCandyFlower("candy_flower");
        FronosBlocks.fronos_coral = new BlockFronosCoral("fronos_coral");
        FronosBlocks.cheese_web = new BlockCheeseWeb("cheese_web");
        FronosBlocks.glass_gem_corn = new BlockGlassGemCorn("glass_gem_corn");
        FronosBlocks.red_maple_ivy = new BlockVineMP("red_maple_ivy");
        FronosBlocks.yellow_maple_ivy = new BlockVineMP("yellow_maple_ivy");
        FronosBlocks.purple_maple_ivy = new BlockVineMP("purple_maple_ivy");
        FronosBlocks.pink_candy_torch = new BlockCandyTorch("pink_candy_torch");
        FronosBlocks.orange_candy_torch = new BlockCandyTorch("orange_candy_torch");
        FronosBlocks.green_candy_torch = new BlockCandyTorch("green_candy_torch");
        FronosBlocks.yellow_candy_torch = new BlockCandyTorch("yellow_candy_torch");
        FronosBlocks.light_blue_candy_torch = new BlockCandyTorch("light_blue_candy_torch");
        FronosBlocks.blue_candy_torch = new BlockCandyTorch("blue_candy_torch");
        FronosBlocks.red_candy_torch = new BlockCandyTorch("red_candy_torch");
        FronosBlocks.purple_candy_torch = new BlockCandyTorch("purple_candy_torch");
        FronosBlocks.cup = new BlockCup("cup_block");
        FronosBlocks.mineral_water_cup = new BlockMineralWaterCup("mineral_water_cup");
        FronosBlocks.ovaltine_cup = new BlockOvaltineCup("ovaltine_cup");
        FronosBlocks.coconut_milk_cup = new BlockCoconutMilkCup("coconut_milk_cup");
        FronosBlocks.cheese_of_milk_cup = new BlockCheeseOfMilkCup("cheese_of_milk_cup");
        FronosBlocks.tea_cup = new BlockTeaCup("tea_cup");
        FronosBlocks.caramel_cup = new BlockCaramelCup("caramel_cup");
        FronosBlocks.coconut_door_block = new BlockDoorMP("coconut_door_block", DoorType.COCONUT);
        FronosBlocks.maple_door_block = new BlockDoorMP("maple_door_block", DoorType.MAPLE);
        FronosBlocks.fronos_sandstone = new BlockFronosSandstone("fronos_sandstone");
        FronosBlocks.half_fronos_sandstone_slab = new BlockFronosSandstoneSlab("half_fronos_sandstone_slab", Material.rock);
        FronosBlocks.double_fronos_sandstone_slab = new BlockDoubleFronosSandstoneSlab("double_fronos_sandstone_slab", Material.rock);
        FronosBlocks.fronos_sandstone_stairs = new BlockStairsMP(Blocks.stone, "fronos_sandstone_stairs", 0.8F);
        FronosBlocks.white_sandstone_stairs = new BlockStairsMP(Blocks.stone, "white_sandstone_stairs", 0.8F);
        FronosBlocks.cheese_sandstone_stairs = new BlockStairsMP(Blocks.stone, "cheese_sandstone_stairs", 0.8F);
        FronosBlocks.fronos_double_tallgrass = new BlockFronosDoubleTallgrass("fronos_double_tallgrass");
        FronosBlocks.sky_mushroom_block = new BlockHugeSkyMushroom("sky_mushroom_block");
        FronosBlocks.cake_farmland = new BlockCakeFarmland("cake_farmland");

        FronosBlocks.coconut_milk_fluid = new FluidMP("coconut_milk_fluid").setBlock(FronosBlocks.coconut_milk).setViscosity(2000);
        FronosBlocks.mineral_water_fluid = new FluidMP("mineral_water_fluid").setBlock(FronosBlocks.mineral_water);
        FronosBlocks.ovaltine_fluid = new FluidMP("ovaltine_fluid").setBlock(FronosBlocks.ovaltine).setViscosity(2000);
        FronosBlocks.tea_fluid = new FluidMP("tea_fluid").setBlock(FronosBlocks.tea).setViscosity(2000);
        FronosBlocks.caramel_fluid = new FluidMP("caramel_fluid").setBlock(FronosBlocks.caramel).setViscosity(3000);
        CommonRegisterHelper.registerFluid(FronosBlocks.coconut_milk_fluid);
        CommonRegisterHelper.registerFluid(FronosBlocks.mineral_water_fluid);
        CommonRegisterHelper.registerFluid(FronosBlocks.ovaltine_fluid);
        CommonRegisterHelper.registerFluid(FronosBlocks.tea_fluid);
        CommonRegisterHelper.registerFluid(FronosBlocks.caramel_fluid);
        FronosBlocks.coconut_milk = new BlockFluidCoconutMilk("coconut_milk_fluid");
        FronosBlocks.mineral_water = new BlockFluidMineralWater("mineral_water_fluid");
        FronosBlocks.ovaltine = new BlockFluidOvaltine("ovaltine_fluid");
        FronosBlocks.tea = new BlockFluidTea("tea_fluid");
        FronosBlocks.caramel = new BlockFluidCaramel("caramel_fluid");

        // Register
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_grass);
        CommonRegisterHelper.registerBlock(FronosBlocks.pink_grass);
        CommonRegisterHelper.registerBlock(FronosBlocks.purple_grass);
        CommonRegisterHelper.registerBlock(FronosBlocks.plains_grass);
        CommonRegisterHelper.registerBlock(FronosBlocks.golden_grass);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_dirt, ItemBlockMultiVariant.class, new VariantsName("dirt", "coarse"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_block, ItemBlockMultiVariant.class, new VariantsName("rock", "cobblestone", "iron_ore", "coal_ore", "aluminum_ore", "tin_ore", "copper_ore", "lapis_ore", "mineral_ore", "black_diamond_ore", "iridium_ore", "stone_brick", "cracked_stone_brick", "chiseled_stone_brick", "dungeon_brick"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_block1, ItemBlockMultiVariant.class, new VariantsName("gold_ore", "diamond_ore", "emerald_ore", "silicon_ore"));
        CommonRegisterHelper.registerBlock(FronosBlocks.jelly_ore, ItemBlockMultiVariant.class, new VariantsName(true, "grape", "raspberry", "strawberry", "berry", "lime", "orange", "green", "lemon"));
        CommonRegisterHelper.registerBlock(FronosBlocks.ore_block, ItemBlockMultiVariant.class, new VariantsName("iridium_block", "black_diamond_block"));
        CommonRegisterHelper.registerBlock(FronosBlocks.frosted_cake, ItemBlockMultiVariant.class, new VariantsName("cake_bread", "white_cake_bread", "chocolate_cake_bread", "frosted_white_cake", "frosted_pink_cake", "frosted_white_cake2", "frosted_chocolate_cake"));
        CommonRegisterHelper.registerBlock(FronosBlocks.jelly_block, ItemBlockMultiVariant.class, new VariantsName(true, "grape", "raspberry", "strawberry", "berry", "lime", "orange", "green", "lemon"));
        CommonRegisterHelper.registerBlock(FronosBlocks.cookie_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.ovaltine_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.chocolate_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.caramel_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.cloud_block, ItemBlockMultiVariant.class, new VariantsName("strawberry", "rainbow"));
        CommonRegisterHelper.registerBlock(FronosBlocks.candy_cane1, ItemBlockCandyCane1.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.candy_cane2, ItemBlockCandyCane2.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.cream_block, ItemBlockMultiVariant.class, new VariantsName(true, "vanilla", "chocolate", "strawberry", "orange", "tea", "lemon"));
        CommonRegisterHelper.registerBlock(FronosBlocks.vanilla_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.vanilla_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.chocolate_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.chocolate_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.strawberry_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.strawberry_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.orange_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.orange_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.tea_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.tea_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.lemon_cream_layer, ItemBlockSnowLayerMP.class, FronosBlocks.lemon_cream_layer);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_sand, ItemBlockMultiVariant.class, new VariantsName("fronos_sand", "white_sand", "cheese_sand"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_sandstone, ItemBlockMultiVariant.class, new VariantsName("fronos_sandstone", "chiseled_fronos_sandstone", "smooth_fronos_sandstone", "white_sandstone", "chiseled_white_sandstone", "smooth_white_sandstone", "cheese_sandstone", "chiseled_cheese_sandstone", "smooth_cheese_sandstone"));
        CommonRegisterHelper.registerBlock(FronosBlocks.half_fronos_sandstone_slab, ItemBlockFronosSandstoneSlab.class, FronosBlocks.half_fronos_sandstone_slab, FronosBlocks.double_fronos_sandstone_slab);
        CommonRegisterHelper.registerBlock(FronosBlocks.double_fronos_sandstone_slab, ItemBlockFronosSandstoneSlab.class, FronosBlocks.half_fronos_sandstone_slab, FronosBlocks.double_fronos_sandstone_slab);
        CommonRegisterHelper.registerBlock(FronosBlocks.cheese_glass);
        CommonRegisterHelper.registerBlock(FronosBlocks.cheese_glass_pane);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_log, ItemBlockFronosLog.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_planks, ItemBlockMultiVariant.class, new VariantsName("coconut", "maple"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_colorized_leaves, ItemBlockFronosColorizedLeaves.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_leaves, ItemBlockMultiVariantLeaves.class, new VariantsName("red_maple_leaves", "yellow_maple_leaves", "purple_maple_leaves"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_cobblestone_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_stone_brick_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.cracked_fronos_stone_brick_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_dungeon_brick_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_sandstone_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.white_sandstone_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.cheese_sandstone_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_wood_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.maple_wood_stairs);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_fence, ItemBlockMultiVariant.class, new VariantsName("coconut", "maple"));
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_fence_gate);
        CommonRegisterHelper.registerBlock(FronosBlocks.maple_fence_gate);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_treasure_chest);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_ancient_chest);
        CommonRegisterHelper.registerBlock(FronosBlocks.candy_extractor_idle);
        CommonRegisterHelper.registerBlock(FronosBlocks.mineral_water_generator);
        CommonRegisterHelper.registerBlock(FronosBlocks.candy_extractor_active);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_farmland);
        CommonRegisterHelper.registerBlock(FronosBlocks.strawberry_bush);
        CommonRegisterHelper.registerBlock(FronosBlocks.golden_crops);
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.golem_cream_head, ItemBlockMultiVariant.class, new VariantsName(true, "vanilla", "chocolate", "strawberry", "orange", "tea", "lemon"));
        CommonRegisterHelper.registerBlock(FronosBlocks.cake_bread);
        CommonRegisterHelper.registerBlock(FronosBlocks.white_cake_bread);
        CommonRegisterHelper.registerBlock(FronosBlocks.chocolate_cake_bread);
        CommonRegisterHelper.registerBlock(FronosBlocks.pink_cake);
        CommonRegisterHelper.registerBlock(FronosBlocks.white_cake);
        CommonRegisterHelper.registerBlock(FronosBlocks.chocolate_cake);
        CommonRegisterHelper.registerBlock(FronosBlocks.space_shell, ItemBlockColoredMP.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.space_oyster);
        CommonRegisterHelper.registerBlock(FronosBlocks.cavern_oyster);
        CommonRegisterHelper.registerBlock(FronosBlocks.jelly_slime_egg, ItemBlockMultiVariant.class, new VariantsName(true, "grape", "raspberry", "strawberry", "berry", "lime", "orange", "green", "lemon"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_sapling, ItemBlockMultiVariant.class, new VariantsName("coconut", "red_maple", "yellow_maple", "purple_maple"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_tall_grass, ItemBlockMultiVariant.class, new VariantsName("short_grass", "medium_grass", "tall_grass", "short_pink_grass", "medium_pink_grass", "tall_pink_grass", "short_purple_grass", "medium_purple_grass", "tall_purple_grass", "short_plains_grass", "medium_plains_grass", "tall_plains_grass", "short_golden_grass", "medium_golden_grass", "tall_golden_grass"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_flower, ItemBlockMultiVariant.class, new VariantsName("pink_butter_cup", "orange_butterfly_flower", "yellow_milk_cap", "little_sun_flower", "sky_mushroom", "purple_spike_flower", "jungle_iris", "blue_poison_mushroom", "white_moss"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_dandelion, ItemBlockDandelion.class);
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_poppy, ItemBlockMultiVariant.class, new VariantsName(true, "white", "orange", "purple"));
        CommonRegisterHelper.registerBlock(FronosBlocks.candy_flower, ItemBlockMultiVariant.class, new VariantsName(true, "pink", "orange", "green", "yellow", "light_blue", "blue", "red", "purple"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_coral, ItemBlockMultiVariant.class, new VariantsName("glowing_pink_coral", "colunus_coral"));
        CommonRegisterHelper.registerBlock(FronosBlocks.fronos_double_tallgrass, ItemBlockMultiVariant.class, new VariantsName("fronos", "pink", "purple", "plains", "golden"));
        CommonRegisterHelper.registerBlock(FronosBlocks.cheese_web);
        CommonRegisterHelper.registerBlock(FronosBlocks.glass_gem_corn);
        CommonRegisterHelper.registerBlock(FronosBlocks.red_maple_ivy);
        CommonRegisterHelper.registerBlock(FronosBlocks.yellow_maple_ivy);
        CommonRegisterHelper.registerBlock(FronosBlocks.purple_maple_ivy);
        CommonRegisterHelper.registerBlock(FronosBlocks.pink_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.orange_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.green_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.yellow_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.light_blue_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.blue_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.red_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.purple_candy_torch);
        CommonRegisterHelper.registerBlock(FronosBlocks.cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.mineral_water_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.ovaltine_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_milk_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.cheese_of_milk_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.tea_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.caramel_cup);
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_door_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.maple_door_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.sky_mushroom_block);
        CommonRegisterHelper.registerBlock(FronosBlocks.coconut_milk);
        CommonRegisterHelper.registerBlock(FronosBlocks.mineral_water);
        CommonRegisterHelper.registerBlock(FronosBlocks.ovaltine);
        CommonRegisterHelper.registerBlock(FronosBlocks.tea);
        CommonRegisterHelper.registerBlock(FronosBlocks.caramel);
        CommonRegisterHelper.registerBlock(FronosBlocks.cake_farmland);

        // Set harvest level
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_grass, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_dirt, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_farmland, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.pink_grass, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.purple_grass, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.plains_grass, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.golden_grass, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_sand, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cream_block, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.vanilla_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.chocolate_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.strawberry_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.orange_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.tea_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.lemon_cream_layer, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.ovaltine_block, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.chocolate_block, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cookie_block, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.frosted_cake, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.golem_cream_head, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cake_farmland, "shovel", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_log, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.coconut_block, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_planks, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.coconut_wood_stairs, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.maple_wood_stairs, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_fence, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.coconut_fence_gate, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.maple_fence_gate, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_ancient_chest, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.sky_mushroom_block, "axe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_sandstone, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.jelly_ore, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_cobblestone_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_stone_brick_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cracked_fronos_stone_brick_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_dungeon_brick_stairs, "pickaxe", 1);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.candy_extractor_idle, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.candy_extractor_active, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.mineral_water_generator, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.ore_block, "pickaxe", 2);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.space_oyster, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cavern_oyster, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.half_fronos_sandstone_slab, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.double_fronos_sandstone_slab, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.fronos_sandstone_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.white_sandstone_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cheese_sandstone_stairs, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.space_shell, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.mineral_water_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.ovaltine_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.coconut_milk_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.cheese_of_milk_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.tea_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.caramel_cup, "pickaxe", 0);
        CommonRegisterHelper.setBlockHarvestLevel(FronosBlocks.space_shell, "pickaxe", 0);

        // Set fire burn
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_planks, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_leaves, 30, 60);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_colorized_leaves, 30, 60);
        CommonRegisterHelper.setFireBurn(FronosBlocks.candy_cane1, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.candy_cane2, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.coconut_wood_stairs, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_fence, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.coconut_fence_gate, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.maple_wood_stairs, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.maple_fence_gate, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.coconut_block, 5, 20);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_tall_grass, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_sapling, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_flower, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_dandelion, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.candy_flower, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_poppy, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_double_tallgrass, 60, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.red_maple_ivy, 15, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.yellow_maple_ivy, 15, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.purple_maple_ivy, 15, 100);
        CommonRegisterHelper.setFireBurn(FronosBlocks.fronos_log, 5, 5);

        // Register ore dictionary
        OreDictionary.registerOre("oreIron", new ItemStack(FronosBlocks.fronos_block, 1, 2));
        OreDictionary.registerOre("oreCoal", new ItemStack(FronosBlocks.fronos_block, 1, 3));
        OreDictionary.registerOre("oreAluminum", new ItemStack(FronosBlocks.fronos_block, 1, 4));
        OreDictionary.registerOre("oreAluminium", new ItemStack(FronosBlocks.fronos_block, 1, 4));
        OreDictionary.registerOre("oreTin", new ItemStack(FronosBlocks.fronos_block, 1, 5));
        OreDictionary.registerOre("oreCopper", new ItemStack(FronosBlocks.fronos_block, 1, 6));
        OreDictionary.registerOre("oreLapis", new ItemStack(FronosBlocks.fronos_block, 1, 7));
        OreDictionary.registerOre("oreMineral", new ItemStack(FronosBlocks.fronos_block, 1, 8));
        OreDictionary.registerOre("oreBlackDiamond", new ItemStack(FronosBlocks.fronos_block, 1, 9));
        OreDictionary.registerOre("oreIridium", new ItemStack(FronosBlocks.fronos_block, 1, 10));
        OreDictionary.registerOre("oreGold", new ItemStack(FronosBlocks.fronos_block1, 1, 0));
        OreDictionary.registerOre("oreDiamond", new ItemStack(FronosBlocks.fronos_block1, 1, 1));
        OreDictionary.registerOre("oreEmerald", new ItemStack(FronosBlocks.fronos_block1, 1, 2));
        OreDictionary.registerOre("oreSilicon", new ItemStack(FronosBlocks.fronos_block1, 1, 3));
        OreDictionary.registerOre("oreJelly", FronosBlocks.jelly_ore);
        OreDictionary.registerOre("cobblestone", new ItemStack(FronosBlocks.fronos_block, 1, 1));
        OreDictionary.registerOre("sand", FronosBlocks.fronos_sand);
        OreDictionary.registerOre("plankWood", new ItemStack(FronosBlocks.fronos_planks, 1, OreDictionary.WILDCARD_VALUE));
        OreDictionary.registerOre("stairWood", new ItemStack(FronosBlocks.coconut_wood_stairs));
        OreDictionary.registerOre("stairWood", new ItemStack(FronosBlocks.maple_wood_stairs));
        OreDictionary.registerOre("treeSapling", new ItemStack(FronosBlocks.fronos_sapling, 1, OreDictionary.WILDCARD_VALUE));
        OreDictionary.registerOre("treeLeaves", new ItemStack(FronosBlocks.fronos_colorized_leaves, 1, OreDictionary.WILDCARD_VALUE));
        OreDictionary.registerOre("treeLeaves", new ItemStack(FronosBlocks.fronos_leaves, 1, OreDictionary.WILDCARD_VALUE));
        OreDictionary.registerOre("logWood", new ItemStack(FronosBlocks.fronos_log, 1, OreDictionary.WILDCARD_VALUE));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane1, 1, 0));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane1, 1, 1));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane1, 1, 2));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane1, 1, 3));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane2, 1, 0));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane2, 1, 1));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane2, 1, 2));
        OreDictionary.registerOre("candyCane", new ItemStack(FronosBlocks.candy_cane2, 1, 3));
        OreDictionary.registerOre("fronosSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 0));
        OreDictionary.registerOre("fronosSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 1));
        OreDictionary.registerOre("fronosSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 2));
        OreDictionary.registerOre("whiteSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 3));
        OreDictionary.registerOre("whiteSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 4));
        OreDictionary.registerOre("whiteSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 5));
        OreDictionary.registerOre("cheeseSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 6));
        OreDictionary.registerOre("cheeseSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 7));
        OreDictionary.registerOre("cheeseSandstone", new ItemStack(FronosBlocks.fronos_sandstone, 1, 8));
        OreDictionary.registerOre("blockIridium", new ItemStack(FronosBlocks.ore_block, 1, 0));
        OreDictionary.registerOre("blockBlackDiamond", new ItemStack(FronosBlocks.ore_block, 1, 1));
    }
}